version: "3.8"

services:
  backend-db-service:
    container_name: backend-db-service
    image: postgres:15.4
    restart: always

    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data_backend:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  backend-service:
    container_name: backend-service
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend-db-service:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    volumes:
      - ./backend/uploads:/app/uploads
    expose:
      - "8080"
    depends_on:
      backend-db-service:
        condition: service_healthy
volumes:
  data_backend:
